export const SIMULATORS = [
  {
    id: 'distillation',
    name: 'Distillation Column',
    tagline: 'Binary & multicomponent column design from VLE to mechanical sizing.',
    models: ['McCabe-Thiele', 'Fenske-Underwood-Gilliland', 'Fair / GPDC', "O'Connell"],
    color: '#2563eb',
    tags: ['VLE', 'Tray', 'Packed', 'Energy'],
  },
  {
    id: 'heat-exchanger',
    name: 'Heat Exchanger',
    tagline: 'Shell & tube design with full Bell-Delaware shell-side analysis.',
    models: ['Bell-Delaware', 'LMTD / F-factor', 'Sieder-Tate', 'Connors vibration'],
    color: '#16a34a',
    tags: ['Condenser', 'Reboiler', 'Vibration', 'ASME'],
  },
  {
    id: 'reactor',
    name: 'Reactor Design',
    tagline: 'Batch, CSTR, PFR, fixed bed — kinetics, stability and economics.',
    models: ['Arrhenius', 'Ergun equation', 'Thiele / Aris', 'Semenov'],
    color: '#dc2626',
    tags: ['CSTR', 'PFR', 'Batch', 'Fixed Bed'],
  },
  {
    id: 'pressure-vessel',
    name: 'Pressure Vessel',
    tagline: 'ASME VIII Div. 1 — five head types, nozzles, relief, wind & seismic.',
    models: ['ASME UG-27', 'UG-37 Nozzle', 'API 520/521', 'ASCE 7'],
    color: '#ea580c',
    tags: ['Heads', 'Flanges', 'PSV', 'Seismic'],
  },
  {
    id: 'mixer',
    name: 'Mixer & Agitator',
    tagline: 'Power, blend time, jacket heat transfer and scale-up rules.',
    models: ['Grenville blend time', 'Bondy-Lippa Nu', 'Kenics ΔP', 'Zwietering'],
    color: '#0891b2',
    tags: ['Power', 'Blending', 'Scale-up', 'Static Mixer'],
  },
  {
    id: 'storage-tank',
    name: 'Storage Tank',
    tagline: 'API 650 shell, roof, floating roof, venting and foundation design.',
    models: ['API 650 1-foot', 'API 2000 venting', 'API 521 fire', 'Towler cost'],
    color: '#ca8a04',
    tags: ['Fixed Roof', 'Floating Roof', 'Foundation', 'Venting'],
  },
  {
    id: 'piping',
    name: 'Piping & Valves',
    tagline: 'Economic diameter, Darcy-Weisbach, control valve Cv and PSV sizing.',
    models: ['Swamee-Jain', 'ISA Cv / Kv', 'API 520 PSV', 'Sinnott-Towler d_opt'],
    color: '#15803d',
    tags: ['Liquid', 'Gas', 'Control Valve', 'Relief'],
  },
  {
    id: 'separations',
    name: 'Separations',
    tagline: 'Absorption, stripping, extraction, crystallisation and drying.',
    models: ['Kremser equation', 'McCabe yield', 'NTU-HTU', 'Drying rate'],
    color: '#a21caf',
    tags: ['Absorption', 'Extraction', 'Crystallisation', 'Drying'],
  },
  {
    id: 'meb',
    name: 'Material & Energy Balance',
    tagline: 'Overall MEB, heat of reaction, Dulong combustion and Rankine cycle.',
    models: ['Stoichiometry', 'Dulong HHV', 'Rankine cycle', 'Energy balance'],
    color: '#1d4ed8',
    tags: ['MEB', 'Combustion', 'Steam', 'Reaction'],
  },
]
